-- Backfill MX rider bikes from Fox Raceway Round 1 entry lists (2026-05-29)
-- Many riders had a null team, so the draft board showed no manufacturer icon.
-- Sets rider_series.team to the entry-list bike (contains the brand, which
-- drives the TeamLogo manufacturer color). Only fills NULLs, so existing
-- factory team names are preserved. Idempotent.

WITH bikes(name, bike) AS (VALUES
  ('Cooper Webb', 'Yamaha YZ450F'),
  ('Chase Sexton', 'Kawasaki KX450SR'),
  ('Dylan Ferrandis', 'Ducati Desmo 450MX'),
  ('Jett Lawrence', 'Honda CRF450R Works Edition'),
  ('Jordon Smith', 'Triumph TF 450-X'),
  ('Christian Craig', 'Honda CRF450R'),
  ('Mikkel Haarup', 'Triumph TF 450-X'),
  ('Justin Cooper', 'Yamaha YZ450F'),
  ('Garrett Marchbanks', 'Kawasaki KX450SR'),
  ('Haiden Deegan', 'Yamaha YZ450F'),
  ('Valentin Guillod', 'Yamaha YZ450F'),
  ('Mitchell Harrison', 'Kawasaki KX450'),
  ('Colt Nichols', 'Suzuki RM-Z450'),
  ('Lorenzo Locurcio', 'GasGas MC 450F Factory Edition'),
  ('Justin Barcia', 'Ducati Desmo 450MX'),
  ('Mitchell Oldenburg', 'Beta 450 RX'),
  ('Benny Bloss', 'Beta 450 RX'),
  ('Grant Harlan', 'KTM 450 SX-F'),
  ('Fredrik Noren', 'Yamaha YZ450F'),
  ('Jack Chambers', 'Kawasaki KX450'),
  ('Kyle Webster', 'Honda CRF450R'),
  ('Justin Rodbell', 'Honda CRF450R'),
  ('Hunter Lawrence', 'Honda CRF450R Works Edition'),
  ('Dominic DeSimone', 'KTM 450 SX-F Factory Edition'),
  ('Clayton Tucker', 'Yamaha YZ450F'),
  ('Whispern Smith', 'KTM 450 SX-F Factory Edition'),
  ('Josh Mosiman', 'KTM 450 SX-F Factory Edition'),
  ('Hamden Hudson', 'Kawasaki KX450'),
  ('Blake Hoag', 'Honda CRF450R Works Edition'),
  ('Bryce Hammond', 'Yamaha YZ450F'),
  ('Grant Hoffman', 'Yamaha YZ450F'),
  ('Cody Walker', 'KTM 450 SX-F'),
  ('Brett Stralo', 'Yamaha YZ450F'),
  ('Joel Milesevic', 'Yamaha YZ450F'),
  ('Daniel Bortolin', 'GasGas MC 450F Factory Edition'),
  ('Cory Carsten', 'Suzuki RM-Z450'),
  ('Konnor Visger', 'Beta 450 RX'),
  ('Myles Monty', 'Yamaha YZ450F'),
  ('Damon Strobel', 'Yamaha YZ450F'),
  ('Cody Wingardner', 'KTM 450 SX-F Factory Edition'),
  ('Dakota Bender', 'Yamaha YZ450F'),
  ('Cornelius Tøndel', 'Kawasaki KX450'),
  ('Mason Semmens', 'KTM 450 SX-F'),
  ('Vincent Luhovey', 'Kawasaki KX450SR'),
  ('Noah Miesen', 'Yamaha YZ450F'),
  ('Magnus Smith', 'Yamaha YZ450F'),
  ('Ethan Day', 'Kawasaki KX450'),
  ('Jack Badell', 'KTM 450 SX-F Factory Edition'),
  ('KC Clinton', 'Honda CRF450R'),
  ('Ryan Surratt', 'Honda CRF450R'),
  ('Rocco Morse', 'Honda CRF450R'),
  ('Gavin Tilford', 'Honda CRF450R'),
  ('Dante Oliveira', 'KTM 450 SX-F'),
  ('RJ Warda', 'KTM 450 SX-F Factory Edition'),
  ('Matt Jackson', 'Husqvarna FC 450 Rockstar Edition'),
  ('Matthew Hubert', 'Kawasaki KX450'),
  ('Anton Nordstrom', 'KTM 450 SX-F'),
  ('Gavin Brough', 'Honda CRF450R'),
  ('Dayton Briggs', 'Yamaha YZ450F'),
  ('Sage Powers', 'Honda CRF450R'),
  ('Anthony Castaneda', 'Yamaha YZ450F'),
  ('Brian Medeiros', 'GasGas MC 450F Factory Edition'),
  ('Seth Hammaker', 'Kawasaki KX250'),
  ('Max Vohland', 'Yamaha YZ250F'),
  ('Coty Schock', 'Yamaha YZ250F'),
  ('Michael Mosiman', 'Yamaha YZ250F'),
  ('Nate Thrasher', 'Yamaha YZ250F'),
  ('Chance Hymas', 'Honda CRF250R Works Edition'),
  ('Jo Shimoda', 'Honda CRF250R Works Edition'),
  ('Austin Forkner', 'Triumph TF 250-X'),
  ('Ryder DiFrancesco', 'Husqvarna FC 250 Factory Edition'),
  ('Cole Davies', 'Yamaha YZ250F'),
  ('Parker Ross', 'Yamaha YZ250F'),
  ('Dilan Schwartz', 'Yamaha YZ250F'),
  ('Lux Turner', 'Yamaha YZ250F'),
  ('Levi Kitchen', 'Kawasaki KX250'),
  ('Avery Long', 'KTM 250 SX-F'),
  ('Max Anstie', 'Yamaha YZ250F'),
  ('Marshal Weltin', 'Kawasaki KX250'),
  ('Carson Mumford', 'KTM 250 SX-F'),
  ('Gavin Towers', 'Honda CRF250R'),
  ('Gage Linville', 'Triumph TF 250-X'),
  ('Derek Kelley', 'Kawasaki KX250'),
  ('Caden Dudney', 'Yamaha YZ250F'),
  ('Kayden Minear', 'Yamaha YZ250F'),
  ('Tim Jaunin', 'Honda CRF250R'),
  ('Russell Buccheri', 'KTM 250 SX-F Factory Edition'),
  ('Nick Romano', 'Kawasaki KX250'),
  ('Cameron McAdoo', 'Kawasaki KX250'),
  ('Dylan Cunha', 'Husqvarna FC 250 Factory Edition'),
  ('Tre Fierro III', 'Yamaha YZ250F'),
  ('Brock Bennett', 'Husqvarna FC 250'),
  ('Landen Gordon', 'Yamaha YZ250F'),
  ('Deacon Denno', 'Triumph TF 250-X'),
  ('Timothy Barnum', 'Husqvarna FC 250 Rockstar Edition'),
  ('Patrick Murphy', 'Yamaha YZ250F'),
  ('Kyle Czworkowski', 'Honda CRF250R'),
  ('Devin Ruth', 'Triumph TF 250-X'),
  ('Collin Burns', 'Kawasaki KX250'),
  ('Joey De Santi', 'Yamaha YZ250F'),
  ('Jonathan Getz', 'Husqvarna FC 250 Factory Edition'),
  ('Ty Freehill', 'Honda CRF250R'),
  ('Nicholas Hunt', 'Triumph TF 250-X'),
  ('Chase Haynes', 'Kawasaki KX250'),
  ('Gavin Betts', 'Kawasaki KX250'),
  ('Brandon Ray', 'Triumph TF 250-X'),
  ('Noah Gordon', 'KTM 250 SX-F'),
  ('Kyle Looney', 'Triumph TF 250-X'),
  ('Cole Timboe', 'Yamaha YZ250F'),
  ('Aden Keefer', 'Honda CRF250R'),
  ('Matthew Mowery', 'KTM 250 SX-F Factory Edition'),
  ('Cole Zeller', 'KTM 250 SX-F'),
  ('Noah Schuring', 'Yamaha YZ250F'),
  ('Alex Andreis', 'GasGas MC 125'),
  ('Carson Millikan', 'Yamaha YZ250F'),
  ('Jace Allred', 'KTM 250 SX-F'),
  ('Jeremy Fappani', 'KTM 250 SX-F'),
  ('CJ Benard', 'Yamaha YZ250F'),
  ('Jace Hinrichs', 'Yamaha YZ250F'),
  ('Preston Masciangelo', 'KTM 250 SX-F'),
  ('Brayden Ehlermann', 'GasGas MC 250F Factory Edition'),
  ('Mathys Boisrame', 'KTM 250 SX-F'),
  ('Keegan Rowley', 'Yamaha YZ250F'),
  ('Cohen Jackman', 'KTM 250 SX-F'),
  ('Jadyn Serles', 'Yamaha YZ250F'),
  ('Nico Israel', 'Triumph TF 250-X'),
  ('Jesse Jacobsen', 'KTM 250 SX-F')
)
UPDATE rider_series rs
SET team = b.bike
FROM bikes b
JOIN riders r ON lower(r.name) = lower(b.name)
WHERE rs.series = 'mx' AND rs.rider_id = r.id AND rs.team IS NULL;
